model:
  type: layout_diffusion.layout_diffusion_unet.LayoutDiffusionUNetModel
  parameters:
    image_size: 32
    use_fp16: True
    use_scale_shift_norm: True
    in_channels: 4
    out_channels: 8
    model_channels: 256
    encoder_channels: 256 # assert same as layout_encoder.hidden_dim
    num_head_channels: 32
    num_heads: -1
    num_heads_upsample: -1
    num_res_blocks: 2
    num_attention_blocks: 1
    resblock_updown: True
    attention_ds: [4, 2, 1]
    channel_mult: [1, 2, 4]
    dropout: 0.0
    use_checkpoint: False
    use_positional_embedding_for_attention: True
    attention_block_type: "ObjectAwareCrossAttention"

    layout_encoder:
      #type: layout_diffusion.layout_encoder.LayoutTransformerEncoder
      type: layout_encoder.LayoutTransformerEncoder
      parameters:
        used_condition_types: ["obj_class", "obj_bbox", "is_valid_obj"]
        hidden_dim: 768 # 256
        output_dim: 1536 # 1024 # model_channels x 4
        num_layers: 6
        num_heads: 8
        use_final_ln: True
        use_positional_embedding: False
        resolution_to_attention: [8, 16, 32]
        use_key_padding_mask: False

diffusion:
  type: layout_diffusion.respace.SpacedDiffusion
  parameters:
    model_var_type: "LEARNED_RANGE"
    model_mean_type: "EPSILON"
    diffusion_steps: 1000
    noise_schedule: "linear"
    learn_sigma: True
    timestep_respacing: [1000]
    loss: ["RESCALED_MSE"]

schedule_sampler:
  type: layout_diffusion.resample.UniformSampler

data:
  type: "WUI"
  parameters:
    split_file: "/content/train_split_web70k.json"
    boxes_dir: "/content/webui-boxes/all_data"
    rawdata_screenshots_dir: "/content/ds_all"
    class_map_file: "/content/LayoutDiffusion/class_map.json"
    max_boxes: 100
    layout_length: 100
    num_classes_for_layout_object: 82
    mask_size_for_layout_object: 128
    loader_num_workers: 10
    used_condition_types: ["obj_class", "obj_bbox"]
    image_size: 256

    train:
      batch_size: 36
      shuffle: True
    val:
      batch_size: 36
      shuffle: False
    test:
      batch_size: 36
      shuffle: False
